apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: pipelinerun-git-clone-build-push-deploy-
spec:
  taskRunTemplate:
    serviceAccountName: pipeline
  pipelineRef:
    name: pipeline-git-clone-build-push-deploy
  params:
  - name: repo-url
    value: https://github.com/koustavsaha/spring-boot-docker/
  - name: tag-name
    value: master
  - name: image-full-path-with-tag
    value: docker.io/koustavs18/springboot-app:latest
  - name: deployment-manifest
    value: https://raw.githubusercontent.com/koustavsaha/spring-boot-docker/master/TektonPipelines/Resources/deployment.yaml
  workspaces:
  - name: maven-settings
    configmap:
      name: maven-settings
  - name: workspace
    persistentvolumeclaim:
      claimName: shared-workspace
  - name: docker-cred
    secret:
      secretName: docker-secret
  - name: empty-dir
    emptyDir: {}
      
